special_keys = {
    "Backspace": {"code": "Backspace", "keyCode": 8, "native_virtual_key_code": 8},
    "Tab": {"code": "Tab", "keyCode": 9, "native_virtual_key_code": 9},
    "Enter": {"code": "Enter", "keyCode": 13, "native_virtual_key_code": 13},
    "Shift": {"code": "ShiftLeft", "keyCode": 16, "native_virtual_key_code": 16},
    "Control": {"code": "ControlLeft", "keyCode": 17, "native_virtual_key_code": 17},
    "Alt": {"code": "AltLeft", "keyCode": 18, "native_virtual_key_code": 18},
    "Pause": {"code": "Pause", "keyCode": 19, "native_virtual_key_code": 19},
    "CapsLock": {"code": "CapsLock", "keyCode": 20, "native_virtual_key_code": 20},
    "Escape": {"code": "Escape", "keyCode": 27, "native_virtual_key_code": 27},
    "Space": {"code": "Space", "keyCode": 32, "native_virtual_key_code": 32},
    "PageUp": {"code": "PageUp", "keyCode": 33, "native_virtual_key_code": 33},
    "PageDown": {"code": "PageDown", "keyCode": 34, "native_virtual_key_code": 34},
    "End": {"code": "End", "keyCode": 35, "native_virtual_key_code": 35},
    "Home": {"code": "Home", "keyCode": 36, "native_virtual_key_code": 36},
    "ArrowLeft": {"code": "ArrowLeft", "keyCode": 37, "native_virtual_key_code": 37},
    "ArrowUp": {"code": "ArrowUp", "keyCode": 38, "native_virtual_key_code": 38},
    "ArrowRight": {"code": "ArrowRight", "keyCode": 39, "native_virtual_key_code": 39},
    "ArrowDown": {"code": "ArrowDown", "keyCode": 40, "native_virtual_key_code": 40},
    "PrintScreen": {"code": "PrintScreen", "keyCode": 44, "native_virtual_key_code": 44},
    "Insert": {"code": "Insert", "keyCode": 45, "native_virtual_key_code": 45},
    "Delete": {"code": "Delete", "keyCode": 46, "native_virtual_key_code": 46},
}


all_characters = {
    "0": {"code": "Digit0", "keyCode": 48, "native_virtual_key_code": 48, "unmodified_text": "0"},
    "1": {"code": "Digit1", "keyCode": 49, "native_virtual_key_code": 49, "unmodified_text": "1"},
    "2": {"code": "Digit2", "keyCode": 50, "native_virtual_key_code": 50, "unmodified_text": "2"},
    "3": {"code": "Digit3", "keyCode": 51, "native_virtual_key_code": 51, "unmodified_text": "3"},
    "4": {"code": "Digit4", "keyCode": 52, "native_virtual_key_code": 52, "unmodified_text": "4"},
    "5": {"code": "Digit5", "keyCode": 53, "native_virtual_key_code": 53, "unmodified_text": "5"},
    "6": {"code": "Digit6", "keyCode": 54, "native_virtual_key_code": 54, "unmodified_text": "6"},
    "7": {"code": "Digit7", "keyCode": 55, "native_virtual_key_code": 55, "unmodified_text": "7"},
    "8": {"code": "Digit8", "keyCode": 56, "native_virtual_key_code": 56, "unmodified_text": "8"},
    "9": {"code": "Digit9", "keyCode": 57, "native_virtual_key_code": 57, "unmodified_text": "9"},

    'a': {'code': 'KeyA', 'keyCode': 65, 'native_virtual_key_code': 97, 'unmodified_text': 'a'},
    'b': {'code': 'KeyB', 'keyCode': 66, 'native_virtual_key_code': 98, 'unmodified_text': 'b'},
    'c': {'code': 'KeyC', 'keyCode': 67, 'native_virtual_key_code': 99, 'unmodified_text': 'c'},
    'd': {'code': 'KeyD', 'keyCode': 68, 'native_virtual_key_code': 100, 'unmodified_text': 'd'},
    'e': {'code': 'KeyE', 'keyCode': 69, 'native_virtual_key_code': 101, 'unmodified_text': 'e'},
    'f': {'code': 'KeyF', 'keyCode': 70, 'native_virtual_key_code': 102, 'unmodified_text': 'f'},
    'g': {'code': 'KeyG', 'keyCode': 71, 'native_virtual_key_code': 103, 'unmodified_text': 'g'},
    'h': {'code': 'KeyH', 'keyCode': 72, 'native_virtual_key_code': 104, 'unmodified_text': 'h'},
    'i': {'code': 'KeyI', 'keyCode': 73, 'native_virtual_key_code': 105, 'unmodified_text': 'i'},
    'j': {'code': 'KeyJ', 'keyCode': 74, 'native_virtual_key_code': 106, 'unmodified_text': 'j'},
    'k': {'code': 'KeyK', 'keyCode': 75, 'native_virtual_key_code': 107, 'unmodified_text': 'k'},
    'l': {'code': 'KeyL', 'keyCode': 76, 'native_virtual_key_code': 108, 'unmodified_text': 'l'},
    'm': {'code': 'KeyM', 'keyCode': 77, 'native_virtual_key_code': 109, 'unmodified_text': 'm'},
    'n': {'code': 'KeyN', 'keyCode': 78, 'native_virtual_key_code': 110, 'unmodified_text': 'n'},
    'o': {'code': 'KeyO', 'keyCode': 79, 'native_virtual_key_code': 111, 'unmodified_text': 'o'},
    'p': {'code': 'KeyP', 'keyCode': 80, 'native_virtual_key_code': 112, 'unmodified_text': 'p'},
    'q': {'code': 'KeyQ', 'keyCode': 81, 'native_virtual_key_code': 113, 'unmodified_text': 'q'},
    'r': {'code': 'KeyR', 'keyCode': 82, 'native_virtual_key_code': 114, 'unmodified_text': 'r'},
    's': {'code': 'KeyS', 'keyCode': 83, 'native_virtual_key_code': 115, 'unmodified_text': 's'},
    't': {'code': 'KeyT', 'keyCode': 84, 'native_virtual_key_code': 116, 'unmodified_text': 't'},
    'u': {'code': 'KeyU', 'keyCode': 85, 'native_virtual_key_code': 117, 'unmodified_text': 'u'},
    'v': {'code': 'KeyV', 'keyCode': 86, 'native_virtual_key_code': 118, 'unmodified_text': 'v'},
    'w': {'code': 'KeyW', 'keyCode': 87, 'native_virtual_key_code': 119, 'unmodified_text': 'w'},
    'x': {'code': 'KeyX', 'keyCode': 88, 'native_virtual_key_code': 120, 'unmodified_text': 'x'},
    'y': {'code': 'KeyY', 'keyCode': 89, 'native_virtual_key_code': 121, 'unmodified_text': 'y'},
    'z': {'code': 'KeyZ', 'keyCode': 90, 'native_virtual_key_code': 122, 'unmodified_text': 'z'},


    "A": {"code": "KeyA", "keyCode": 65, "native_virtual_key_code": 65, "unmodified_text": "a"},
    "B": {"code": "KeyB", "keyCode": 66, "native_virtual_key_code": 66, "unmodified_text": "b"},
    "C": {"code": "KeyC", "keyCode": 67, "native_virtual_key_code": 67, "unmodified_text": "c"},
    "D": {"code": "KeyD", "keyCode": 68, "native_virtual_key_code": 68, "unmodified_text": "d"},
    "E": {"code": "KeyE", "keyCode": 69, "native_virtual_key_code": 69, "unmodified_text": "e"},
    "F": {"code": "KeyF", "keyCode": 70, "native_virtual_key_code": 70, "unmodified_text": "f"},
    "G": {"code": "KeyG", "keyCode": 71, "native_virtual_key_code": 71, "unmodified_text": "g"},
    "H": {"code": "KeyH", "keyCode": 72, "native_virtual_key_code": 72, "unmodified_text": "h"},
    "I": {"code": "KeyI", "keyCode": 73, "native_virtual_key_code": 73, "unmodified_text": "i"},
    "J": {"code": "KeyJ", "keyCode": 74, "native_virtual_key_code": 74, "unmodified_text": "j"},
    "K": {"code": "KeyK", "keyCode": 75, "native_virtual_key_code": 75, "unmodified_text": "k"},
    "L": {"code": "KeyL", "keyCode": 76, "native_virtual_key_code": 76, "unmodified_text": "l"},
    "M": {"code": "KeyM", "keyCode": 77, "native_virtual_key_code": 77, "unmodified_text": "m"},
    "N": {"code": "KeyN", "keyCode": 78, "native_virtual_key_code": 78, "unmodified_text": "n"},
    "O": {"code": "KeyO", "keyCode": 79, "native_virtual_key_code": 79, "unmodified_text": "o"},
    "P": {"code": "KeyP", "keyCode": 80, "native_virtual_key_code": 80, "unmodified_text": "p"},
    "Q": {"code": "KeyQ", "keyCode": 81, "native_virtual_key_code": 81, "unmodified_text": "q"},
    "R": {"code": "KeyR", "keyCode": 82, "native_virtual_key_code": 82, "unmodified_text": "r"},
    "S": {"code": "KeyS", "keyCode": 83, "native_virtual_key_code": 83, "unmodified_text": "s"},
    "T": {"code": "KeyT", "keyCode": 84, "native_virtual_key_code": 84, "unmodified_text": "t"},
    "U": {"code": "KeyU", "keyCode": 85, "native_virtual_key_code": 85, "unmodified_text": "u"},
    "V": {"code": "KeyV", "keyCode": 86, "native_virtual_key_code": 86, "unmodified_text": "v"},
    "W": {"code": "KeyW", "keyCode": 87, "native_virtual_key_code": 87, "unmodified_text": "w"},
    "X": {"code": "KeyX", "keyCode": 88, "native_virtual_key_code": 88, "unmodified_text": "x"},
    "Y": {"code": "KeyY", "keyCode": 89, "native_virtual_key_code": 89, "unmodified_text": "y"},
    "Z": {"code": "KeyZ", "keyCode": 90, "native_virtual_key_code": 90, "unmodified_text": "z"},


    "`":  { "code": "Backquote",     "keyCode": 192, "native_virtual_key_code": 192, "unmodified_text": "`" },
    "-":  { "code": "Minus",         "keyCode": 189, "native_virtual_key_code": 189, "unmodified_text": "-" },
    "=":  { "code": "Equal",         "keyCode": 187, "native_virtual_key_code": 187, "unmodified_text": "=" },
    "[":  { "code": "BracketLeft",   "keyCode": 219, "native_virtual_key_code": 219, "unmodified_text": "[" },
    "]":  { "code": "BracketRight",  "keyCode": 221, "native_virtual_key_code": 221, "unmodified_text": "]" },
    "\\": { "code": "Backslash",     "keyCode": 220, "native_virtual_key_code": 220, "unmodified_text": "\\" },
    ";":  { "code": "Semicolon",     "keyCode": 186, "native_virtual_key_code": 186, "unmodified_text": ";" },
    "'":  { "code": "Quote",         "keyCode": 222, "native_virtual_key_code": 222, "unmodified_text": "'" },
    ",":  { "code": "Comma",         "keyCode": 188, "native_virtual_key_code": 188, "unmodified_text": "," },
    ".":  { "code": "Period",        "keyCode": 190, "native_virtual_key_code": 190, "unmodified_text": "." },
    "/":  { "code": "Slash",         "keyCode": 191, "native_virtual_key_code": 191, "unmodified_text": "/" },


    # Shifted versions — same code, different key/text
    "~":  { "code": "Backquote",     "keyCode": 192, "native_virtual_key_code": 192, "unmodified_text": "`" },
    "!":  { "code": "Digit1",        "keyCode": 49,  "native_virtual_key_code": 49,  "unmodified_text": "1" },
    "@":  { "code": "Digit2",        "keyCode": 50,  "native_virtual_key_code": 50,  "unmodified_text": "2" },
    "#":  { "code": "Digit3",        "keyCode": 51,  "native_virtual_key_code": 51,  "unmodified_text": "3" },
    "$":  { "code": "Digit4",        "keyCode": 52,  "native_virtual_key_code": 52,  "unmodified_text": "4" },
    "%":  { "code": "Digit5",        "keyCode": 53,  "native_virtual_key_code": 53,  "unmodified_text": "5" },
    "^":  { "code": "Digit6",        "keyCode": 54,  "native_virtual_key_code": 54,  "unmodified_text": "6" },
    "&":  { "code": "Digit7",        "keyCode": 55,  "native_virtual_key_code": 55,  "unmodified_text": "7" },
    "*":  { "code": "Digit8",        "keyCode": 56,  "native_virtual_key_code": 56,  "unmodified_text": "8" },
    "(":  { "code": "Digit9",        "keyCode": 57,  "native_virtual_key_code": 57,  "unmodified_text": "9" },
    ")":  { "code": "Digit0",        "keyCode": 48,  "native_virtual_key_code": 48,  "unmodified_text": "0" },
    "_":  { "code": "Minus",         "keyCode": 189, "native_virtual_key_code": 189, "unmodified_text": "-" },
    "+":  { "code": "Equal",         "keyCode": 187, "native_virtual_key_code": 187, "unmodified_text": "=" },
    "{":  { "code": "BracketLeft",   "keyCode": 219, "native_virtual_key_code": 219, "unmodified_text": "[" },
    "}":  { "code": "BracketRight",  "keyCode": 221, "native_virtual_key_code": 221, "unmodified_text": "]" },
    "|":  { "code": "Backslash",     "keyCode": 220, "native_virtual_key_code": 220, "unmodified_text": "\\" },
    ":":  { "code": "Semicolon",     "keyCode": 186, "native_virtual_key_code": 186, "unmodified_text": ";" },
    "\"": { "code": "Quote",         "keyCode": 222, "native_virtual_key_code": 222, "unmodified_text": "'" },
    "<":  { "code": "Comma",         "keyCode": 188, "native_virtual_key_code": 188, "unmodified_text": "," },
    ">":  { "code": "Period",        "keyCode": 190, "native_virtual_key_code": 190, "unmodified_text": "." },
    "?":  { "code": "Slash",         "keyCode": 191, "native_virtual_key_code": 191, "unmodified_text": "/" }
}